apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordlesolver-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: wordlesolver
  template:
    metadata:
      labels:
        app: wordlesolver
    spec:
      containers:
        - name: wordlesolver
          image: swarooprooney/wordlesolver:v1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: wordlesolver-clusterip-srv
# spec:
#   type: ClusterIP
#   selector: 
#     app: wordlesolver
#   ports: 
#    - name: wordlesolver
#      protocol: TCP
#      port: 80
#      targetPort: 80
#      externalIp: 10.180.121.5
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-srv
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/use-regex: 'true'
# spec:
#   defaultBackend:
#       service:
#         name: wordlesolver-clusterip-srv
#         port:
#           number: 80
  # rules:
  #   - host: swarooprooney.com
  #     http:
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #           backend:
  #             service:
  #               name: platforms-clusterip-srv
  #               port:
  #                 number: 80
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: wordlesolver-lb-srv
# spec:
#   ports:
#     - name: http
#       port: 8080
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: wordlesolver
#   type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: wordlesolver-srv
spec:
  type: NodePort
  selector:
    app: wordlesolver
  ports:
    - name: wordlesolver
      protocol: TCP
      port: 80
      targetPort: 80
